config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new # needed to instantiate the form_for
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @doses = @cocktail.doses
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.delete
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @dose = Dose.new
      render "cocktails/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Edit cocktail</h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="banner-content">
  <h1>Miagani's cocktails</h1>
  <p>Awesome beverages for superheros fans (& sous-doués fans obvi)</p>
  <%= link_to "Add a cocktail", new_cocktail_path, class: "btn btn-primary btn-lg" %>
</div>

<div class="d-flex justify-center">
  <div class="row">
    <% @cocktails.sort.each do |cocktail| %>
      <div class="col-sm-4 col-6">
        <div class="card align-middle m-3 ">
          <% if cocktail.photo.attached? %>
            <%= cl_image_tag cocktail.photo.key, height: 300, width: 400, crop: :fill %>
          <% else  %>
            No Picture
          <% end %>
          <div class="card-body text-center">
            <h5 class="card-title"><%= link_to cocktail.name, cocktail_path(cocktail) %></h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create a new cocktail</h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://wisk.ai/wp-content/uploads/2019/07/liquor-inventory-scale-2.jpg);">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
    <p>Hell of a cocktail!</p>
  </div>
</div>

<div class="container overlap text-align-center">

  <div class="card  align-middle m-3 w-100" style="width: 18rem;">
    <!-- Contains the info about restaurant -->
    <div class="card-body">
      <h3 class="card-title"><%= @cocktail.name %></h5>
      <p class="card-text">Recipe</p>
    </div>
  </div>

  <div class="card align-middle m-3 w-100" style="width: 18rem;">
    <!-- Contains the info about restaurant -->
    <div class="card-body">
      <h3 class="card-title">Info</h3>
      <p class="card-text">Description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi temporibus facilis id nemo aperiam sunt optio doloremque ducimus minus pariatur, tempore numquam dolorum autem culpa ea voluptatum aspernatur, molestiae repellat.</p>
      <% dose = 0 %>
      <% @doses.each do |dose| %>
        <p>
          <%= dose.description %> of <%= dose.ingredient.name %>.
          <%= link_to "Delete", dose_path(dose.id), method: "delete", :class => "btn btn-danger" %>
        </p>
      <% end %>
      <h4><%= link_to "Add doses", new_cocktail_dose_path(@cocktail) %></h4>

     <!--  <%#= simple_form_for [@cocktail, @dose] do |f| %>
        <%#= f.input :description%>
        <%#= f.association :ingredient %>
        <%#= f.submit%>
      <%# end %> -->
      <div style="display: block">
        <p class="card-text"><i class="fas fa-euro-sign"></i>15</p>
        <%= link_to 'Back', cocktails_path, :class => "btn btn-primary" %> |
        <%= link_to 'Edit', edit_cocktail_path(@cocktail), :class => "btn btn-primary" %> |
        <%= link_to 'Delete Cocktail', cocktail_path(@cocktail), method: :delete, :class => "btn btn-primary" %> |
      </div>
    </div>

    <h3>Reviews</h3>
    <% if @cocktail.reviews.empty? %>
      <p>Be the first to let a review</p>
    <% else %>
      <ul class="list-group">
        <% @cocktail.reviews.each do |review| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <span class="badge badge-primary badge-pill">
              <% counter = 0 %>
              <% 5.times do %>
                <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                <% counter += 1 %>
              <% end %>
            </span>
            <%= review.content %>
          </li>
        <% end %>
      </ul>
    <% end %>

    <%= render "reviews/new", cocktail: @cocktail, review: @review %>
  </div>

</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description%>
  <%= f.association :ingredient %>
  <%= f.submit%>
<% end %>

app/views/doses/show.html.erb
<% dose = 0 %>
<% @doses.each do |dose| %>
<p>
  <%= dose.description %> of <%= dose.ingredient.name %>.
  <%= link_to "Delete", dose_path(dose.id), method: "delete", :class => "btn btn-danger" %>
</p>
<% end %>
<h4><%= link_to "Add doses", new_cocktail_dose_path(@cocktail) %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [cocktail, review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to cocktails_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <%= link_to new_cocktail_path, class: "navbar-brand" do %>
    <%= image_tag "add.png" %>
  <% end %>
</div>